//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OZPXMLImport.DataModelSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OZPXMLImportEntities : DbContext
    {
        public OZPXMLImportEntities()
            : base("name=OZPXMLImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pojistovna> Pojistovna { get; set; }
        public virtual DbSet<PoskytovatelZdravotnichSluzeb> PoskytovatelZdravotnichSluzeb { get; set; }
        public virtual DbSet<Smlouva> Smlouva { get; set; }
        public virtual DbSet<TypPZS> TypPZS { get; set; }
        public virtual DbSet<TypSmlouvy> TypSmlouvy { get; set; }
    
        public virtual ObjectResult<GetListOfSmlouva_Result> GetListOfSmlouva(Nullable<System.DateTime> datum)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListOfSmlouva_Result>("GetListOfSmlouva", datumParameter);
        }
    }
}
