//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OZPXMLImport.DataModelSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smlouva
    {
        public int Id { get; set; }
        public int PoskytovatelZdravotnichSluzebId { get; set; }
        public int PojistovnaId { get; set; }
        public System.DateTime DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
        public int TypSmlouvyId { get; set; }
    
        public virtual Pojistovna Pojistovna { get; set; }
        public virtual PoskytovatelZdravotnichSluzeb PoskytovatelZdravotnichSluzeb { get; set; }
        public virtual TypSmlouvy TypSmlouvy { get; set; }
    }
}
